### ISSUE TITLE
Systematic way to update Docker Hub

### ISSUE THREAD

**Issue by dbosk** [repobee/repobee#1027]
Not sure how you do releases, but I noticed that the [images on Docker Hub](https://hub.docker.com/r/repobee/repobee/tags) are a bit out of sync with the actual releases.

I have no idea what would fit RepoBee releasing (I noticed you're an inspiration to all with release documentation). I usually make a release using [`gh`](https://cli.github.com) in a script and then I simultaneously build and push an updated image to Docker Hub too to keep them in sync.

**Comment by slarse** [comment]
Ohhh, that's probably because the free tier of Docker Hub stopped providing automatic repository scanning a while back. I got an email about it and then promptly forgot about it :)

RepoBee is deployed from GitHub Actions when a GitHub release is created ([see deploy.yaml](https://github.com/repobee/repobee/blob/master/.github/workflows/deploy.yml), I'll just have to add in deploying to Docker Hub. Shouldn't be particularly difficult.

**Comment by dbosk** [comment]
That's cool, I should definitely look into deploying with GitHub actions and play around with it!

**Comment by slarse** [comment]
As it turned out, the Docker image wouldn't even build anymore as I'd neglected it for so long. Oopsie.

I've manually backfilled the missing releases and will now turn to automatic deployments. There's a GitHub action from Docker that should do the trick (https://github.com/docker/build-push-action).

**Comment by slarse** [comment]
@dbosk Figured out a deploy workflow for updating latest on each push to master and then (hopefully) releasing a stable release on each GitHub release. The former definitely works now, the latter... Well, we'll see when I make the next release :)
