### ISSUE TITLE
Support specifying groups from the command line

### ISSUE THREAD

**Issue by slarse** [repobee/repobee#163]
To support this, the semantics of the `-s|--student` option needs to change. If `ham` should be solo and `spam` and `eggs` a group, there needs to be some sort of way to differentiate them. Instead of `-s ham spam eggs`, it needs to be something along the lines of `-s ham -s spam eggs`, so all arguments following a `-s` would be a group.

However, then the name `--student` hardly makes sense, so the name should possibly change, but I'm not quite sure what to. The support for group assignments is introducing some amount of terminology confusion to the otherwise simple use of `student`.

As this would be a breaking change, it can't be introduced until RepoBee v2.

The use of `-s` should be deprecated once I've come up with a clean solution for the interface.

**Comment by rjglasse** [comment]
Given how awkward it would be to use the command line for all but the most trivial group situations, perhaps it is better to expand the interface to have an explicit -g --groups option which only permits a single argument, which is a file having a legal group format (1 or more elements per line).

Even though the logic would be the same more or less for the -s --students option, it might be easier to document as it would be two short descriptions of functionality, rather than one option to rule them all.

-s -student could be switched to -i --individual to clean up the interface, except for the fact that -i is already occupied :) and this is the problem with designing interfaces ;)

i guess if the two branches made sense in v2, the -ia and -ga could be used, where 'a' is allocation.

**Comment by slarse** [comment]
The large benefit from expanding the functionality of the `-s` option would actually mostly be from a testing and maintenance perspective, as the command line input and file input can be treated the same way (special cases are a bother). It was when writing tests for the new group functionality that I came up with the idea.

I also think the usability impact from having to specify `-s ham -s spam` instead of `-s ham spam` to specify single students would be minimal. In my day-to-day use, I almost only use the command line to specify one or two students that I want to do grading on (e.g. after komplettering, or to re-run a plugin after having changed their repos). I would personally benefit from being able to specify a single group as well (if I had groups to grade, which I don't at the moment).

Essentially: testing becomes easier, and I think usability impact is minimal at worst. I'm very hesitant about adding new options (see #164), so I'm only seeing two viable options:

1. Limit the command line to single students.
2. Rework the `-s` option (probably renaming it in the process) to work for both groups and single students.

**Comment by slarse** [comment]
I've decided to simply not do this for the time being. It's a possible feature if anyone asks for it.
