### ISSUE TITLE
PluginLoadError: failed to load plugin module defaults

### ISSUE THREAD

**Issue by rjglasse** [repobee/repobee#419]
The same error message is given for any of the commands

```
ric@ric-mbp repobee % repobee verify-settings
[ERROR] PluginLoadError: failed to load plugin module defaults
[ERROR] The plugin may not be installed, or it may not exist. If the plugin is defined in the config file, try running `repobee --no-plugins config-wizard` to remove any offending plugins.
```

Using v2.4.0 on Mac OS 10.15.4

**Comment by slarse** [comment]
This appears to have occurred because of Python breaking in an OS update, causing some modules not to load anymore. Even so, the error message here is subpar. `--traceback` also does not add any information, because errors when loading modules are discarded to be able to try multiple options.

https://github.com/repobee/repobee/blob/bfb4792021be5720e17fbc9ad4b4a9a35c2898eb/src/_repobee/plugin.py#L43-L93

We should collect errors from loading plugin modules, and if a plugin fails to load as both an external and internal module, both of these errors should be propagated up to the user.

**Comment by slarse** [comment]
This technically isn't a bug in RepoBee, so I'm swapping out the label :)
