### ISSUE TITLE
`repobee plugin list` table difficult to read (tables not scaling to terminal width)

### ISSUE THREAD

**Issue by htdebeer** [repobee/repobee#669]
The command `repobee plugin list` gives the following output (see screenshot). Although I appreciate nicely formatted output, this table is not very readable.
![repobee-plugin-list-output](https://user-images.githubusercontent.com/1954802/92605834-7dfc2b00-f2b2-11ea-8d04-319a1fcf7f83.png)

**Comment by slarse** [comment]
That's not what it's supposed to look like, and I'm guessing it's because your terminal isn't wide enough. The tables currently don't scale to the output terminal's width. It looks like this for me:

![plugin_table](https://user-images.githubusercontent.com/14223379/92606261-0bd81600-f2b3-11ea-82c8-ea4fc8c011bb.png)

Do you find anything wrong with that formatting? I'm guessing your complaint was with the absolute mess found in your image :).  Try doubling the width of your terminal and it should be fine.

That being said, it would ideally scale to the terminal width, it's just a little tricky as the underlying library for creating the neat table doesn't help with that. Should I consider this a feature request for output terminal scaling of the (quite frequent) tables?

**Comment by slarse** [comment]
At the very least, there should be a warning saying that the terminal is not wide enough for the table to be displayed correctly.

**Comment by htdebeer** [comment]
Yeah, it is a bit of nitpicking. I like to work on a small-width terminal with a large font. If I change either, it looks fine.

**Comment by slarse** [comment]
It's an entirely valid usability issue that I had already considered, but not bothered with as no one had yet to voice an opinion about it. I personally use a very large (32") monitor with very small font, so it doesn't bother me on a day-to-day basis, but I did have issues on my laptop.

Any suggestions on what to do with the URL? Putting it on two lines will make it a bit of a bother to copy it.

**Comment by htdebeer** [comment]
You can put the columns in rows, but that makes it less compact. Something like 

```
plugin (version, installed)
    description
    URL
```
Or maybe have a verbose and compact version of this command? So only showing the description and URL in the verbose mode?

**Comment by slarse** [comment]
Here's my proposed solution: if the terminal is wide enough, show the entire table. Otherwise, start removing columns in the following order:

1. URL (because this is the widest column)
2. Latest
3. Installed
4. Description
5. Name

Removing the fifth and final column effectively makes the table the empty string, so that should definitely fit any terminal size! A warning is shown for each column that is removed. My prototype looks like this:

![self_truncating_table](https://user-images.githubusercontent.com/14223379/92895062-75733400-f41b-11ea-8244-f29c5eea84b8.png)

The warnings may be a bit annoying, but I want to make it very, very clear that all information is not showing.

@htdebeer WDYT? Is this a good solution to your problem?

**Comment by htdebeer** [comment]
Yes, given the target audience, this seems to be a nice solution.
