### ISSUE TITLE
Add --update-local flag to repos clone command

### ISSUE THREAD

**Issue by Quincunxial** [repobee/repobee#693]
Sometimes you want to see changes to student repos after the initial clone, having the option to overwrite local repos with the master version would be useful.

**Comment by slarse** [comment]
Thanks for the suggestion! This sounds like a pretty neat feature.

I don't think "overwriting" per se is the best thing to do, as that's a bit dangerous. Simply fetching changes to the existing local repo would however be safe, and probably isn't too hard to implement. Unless I'm missing something. So, I'm thinking that with the `--update-local` flag, RepoBee would try to fetch the latest changes into any local repositories (as well as freshly clone any non-local repositories), but would not try to force it if a local repositories has unstashed changes or is otherwise inconsistent with the remote repo.

If we get some more interest in this, I'll just go ahead and implement it. Otherwise, I'll first figure out how tricky it is, and if it turns out to not be too tricky I'll probably implement it anyway. **Anyone else that wants this feature, please upvote (thumbs up emoji) the original post**

**Comment by slarse** [comment]
@Quincunxial Thanks for the suggestion, the `--update-local` flag will become available in RepoBee 3.3.
