### ISSUE TITLE
Loading, creating, and writing RepoBee config files and adding any argument to a RepoBee config file

### ISSUE THREAD

**Issue by iupNZdsLJM** [repobee/repobee#876]
I have created a prototype for an "init-course" command that would take a URL to a Canvas course and then start a wizard to setup a directory for that course. While building this command, it would have been nice to be able:

- to load the current RepoBee config easily
- maybe to load the global RepoBee config as well
- an easy way to construct a fresh RepoBee config and write it to file

You can find this "init-course' command's code [here](https://github.com/htdebeer-tue/repobee-canvas/blob/ebc0675423d4735f7d4c44ff98d5ba1b26214d88/repobee_canvas/init_course.py#L233). It is a bit off a mess now, but I will clean this up when implementing the next feature on my mind: I am planning to make a similar command for setting up an assignment with RepoBee. This "assignment" command would:

- show the user a list of assignments on Canvas to pick one
- show the user a list of template repos on Git to pick one
- create a subdirectory with a RepoBee config file that would refer to the course's RepoBee config file (inheritance, one of the issues you're working on)
- generate a "students.lst" file for use with this assignment

Question, would it be possible for me to add the "--assignments" and "--students-file" arguments as an option to a RepoBee config file? How I envision using the Canvas plugin, the user would create a course directory, and for each assignment on Canvas also a assignment subdirectory. If these RepoBee arguments can be stored in the config file as well, all a user has to do to manage an assignment would be:  "repobee repos setup" and "repobee repos clone". 

That would be nice, plus I hope there are less issues with selecting the wrong students file or assignment template if everything is handled by this "assignments" wizard command the user would run once when starting managing the assignment.

**Comment by slarse** [comment]
Hi @htdebeer-tue!

> * to load the current RepoBee config easily

This is already possible with the [`handle_config` hook](https://docs.repobee.org/en/stable/repobee_plug/code.html?highlight=handle_config#repobee_plug._exthooks.handle_config).

> * maybe to load the global RepoBee config as well

There's currently no built-in support for getting the global config specifically, `handle_config` always gets the most local config. If there's no local config, then that'll always be the global config. Are you sure you need to get the global config specifically? What exactly would be the purpose of that?

> * an easy way to construct a fresh RepoBee config and write it to file

This is technically already possible with the `Config` class, but the interface might slightly change as it needs to be adjusted for inheritance (which I did not anticipate, and there were some complications). At this time, you could rewrite this part: https://github.com/htdebeer-tue/repobee-canvas/blob/ebc0675423d4735f7d4c44ff98d5ba1b26214d88/repobee_canvas/init_course.py#L306-L315

Like so:

```python
import pathlib # strongly recommend you use pathlib for dealing with paths; strings are error-prone

config = plug.Config(pathlib.Path(path))

config.create_section("repobee")
config["repobee"]["template_org_name"] = template
[... set the rest of the options in the same way ...]

config.create_section("canvas")
config["canvas"]["canvas_api_key"] = access_token
[... set the rest of the options in the same way ...]

config.store() # stores the config to the path provided
```

But again, I may need to break that API to make inheritance work well. And I'm not quite sure what the programmatic inheritance access will look like yet, there are some intricacies to it.

Also, you can probably draw some inspiration from the [configwizard.py](https://github.com/repobee/repobee/blob/de8cd774b3b6768c1ca0a6e639010f68af944cc7/src/_repobee/ext/defaults/configwizard.py) plugin (which defines the `config wizard` command).

> You can find this "init-course' command's code [here](https://github.com/htdebeer-tue/repobee-canvas/blob/ebc0675423d4735f7d4c44ff98d5ba1b26214d88/repobee_canvas/init_course.py#L233). It is a bit off a mess now, but I will clean this up when implementing the next feature on my mind: I am planning to make a similar command for setting up an assignment with RepoBee. This "assignment" command would:

I had a brief look, I'll dive deeper sometime after Easter, I'm unfortunately a bit busy until then. I had some immediate feedback, though, see the bottom of this comment.

> Question, would it be possible for me to add the "--assignments" and "--students-file" arguments as an option to a RepoBee config file?

The students file is already configurable in the core RepoBee section (run `config wizard` and you'll see `students_file` as one of the options).

The `--assignments` argument is not currently configurable, we've never had a use case for that. But that's simple enough to add.

### Summary of features needed
So, to summarize, I think this is what's needed:

* Easy way to edit the `[repobee]` section of the config
    - The configurable section name and configurable arguments need to be available in `repobee_plug`
* `--assignments` as a configurable argument
* Stabilization and documentation of the `Config` class
* Programmatic access to inheritance
* Potentially specifically being able to access the global config?

Anything to add?

### Quick feedback on the plugin

* As mentioned, I strongly recommend using [`pathlib`](https://docs.python.org/3/library/pathlib.html) for paths
* I noticed some logging helpers, have you seen the [`repobee_plug.log` module?](https://docs.repobee.org/en/stable/repobee_plug/code.html#module-repobee_plug.log). It provides access to RepoBee's logging facilities, with appropriate color coding and adhering to the stacking `--quiet` option.
* Instead of enclosing the entire command in a `try/except`, it's generally better to let RepoBee catch any unhandled exceptions. That way, the user doesn't get a full stack trace in the face (which can be very intimidating) without specifying the `--traceback` option.

**Comment by htdebeer-tue** [comment]
Thanks for your feedback! As a Python beginner, it is awesome to get some expert input. I will apply those suggestions next week.

I also appreciate your explanation / pointers to using RepoBee Config. That allows me to finish the "init-course" command and with your other remarks, the "init-assignment" command should not be much of a hassle either.

I do not think I do need any other new features at the moment. With what you suggest and you're working on, the setup of the Canvas-RepoBee environment should be covered, as well as the use of the "repos" subcommand. For now, that is the command I am targeting for my try-out of the canvas plugin. 

Enjoy your weeks off! 

Once you're back, I hope to have cleaned up and improved the Canvas plugin. Writing a wizard with the Bullet library that you suggested is a breeze. It took me a moment to get the hang of it, but now that I know its capabilities and limitations, it really speeds up development of wizard like commands. And these wizard like commands are very user friendly compared to applying lots of command-line options with long names and values!

**Comment by slarse** [comment]
You're welcome!

I'll poke my head back in here once non-RepoBee-related things have settled down on my end, which should be in a week or two.

**Comment by slarse** [comment]
Closing as stale.
